# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
    - sc
  workflow_dispatch:

permissions:
      contents: read
      id-token: write
      pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
          
      #- name: Azure PowerShell Action
      #  uses: Azure/powershell@v1
      #  with:
      #    inlineScript: Get-AzResourceGroup -Name "< YOUR RESOURCE GROUP >"
      #    azPSVersion: "latest"
